### ISSUE TITLE
firehose-core is not registering the dmetering null plugin

### ISSUE THREAD

**Issue by fschoell** [streamingfast/firehose-core#10]
Seems like the latest commit changed the registration: https://github.com/streamingfast/firehose-core/commit/00d2eda2b84b02d4ab1742b757b1432ea963573e#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261

But forgot to register the null plugin

**Comment by colindickson** [comment]
fixed in 0.1.6

thank you!
