### ISSUE TITLE
fireacme is hard-coded

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/firehose-core#14]
I saw this message:

```
Error: config file "/etc/dfuse/config.yml" not found. Did you 'fireacme init'?
```

The fact the config file is missing is my problem, but the error shouldn't say fireacme.

https://github.com/streamingfast/firehose-core/blob/cff94677bea714fc9d79c0c7316c2f1a1d617c8c/setup.go#L32

**Comment by maoueh** [comment]
Yep old stuff, `fire<chain> init` don't even make sense anymore, going to re-write the message thanks
