### ISSUE TITLE
Request feature: Ability to control params in rpc request for evm rpc poller

### ISSUE THREAD

**Issue by Johnaverse** [streamingfast/firehose-core#33]
Currently not all the blockchain support "finalized" params for their rpc interface but actually the block is already irreversible. To support more evm chain, It will be great if we can control the params for the rpc request.

**Comment by matthewdarwin** [comment]
Fred did a quick workaround for the EOS-EVM RPC to hard-code the LIB as -200.  But we would need generically need a command line argument to the RPC poller.

**Comment by matthewdarwin** [comment]
This is resolved and can be closed.
