### ISSUE TITLE
firehose-core does not support the  --block-rate flag

### ISSUE THREAD

**Issue by taobig** [streamingfast/firehose-core#59]
https://github.com/streamingfast/firehose-core/blob/ad3d137d66d498e1a369b6f80dbd36718028d5f6/devel/standard/standard.yaml#L21

**Comment by maoueh** [comment]
That is an arguments that is passed to the "node" itself. Everything under `reader-node-arguments` is pass down to the node process `firehose-core` instance is managing.

In the example file you listed, the binary is defined by `reader-node-path: "dummy-blockchain"`. The binary `dummy-blockchain` emulates what a real blockchain would do but for development purposes so it emits fake data. The project can be found at https://github.com/streamingfast/dummy-blockchain?tab=readme-ov-file#dummy-chain.

If you want to run the `devel/standard/start.sh` script for development purposes, the instructions are:

```
# This enables `firecore` command to use `./devel/firecore` script which compiles then run
export PATH="`pwd`/devel:$PATH"

# Needed only once, if you don't have the binary locally already
go install github.com/streamingfast/dummy-blockchain@latest

./devel/standard/start.sh
```
