### ISSUE TITLE
prometheus exporter does not include tier1 or tier2 in the "ready" status

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/firehose-core#6]
The prometheus exporter does not include susbtreams tier1 or tier2 in the "ready" status.

Seen on substreams tier2, for example:

```
# HELP ready readiness of an app. 1 if ready, 0 otherwise
# TYPE ready gauge
ready{app="block-indexer"} 0
ready{app="firehose"} 0
ready{app="merger"} 0
ready{app="relayer"} 0
```

Was previously: https://github.com/streamingfast/firehose-ethereum/issues/67

**Comment by maoueh** [comment]
So essentially you are missing the readyness metric for `substreams-tier1` and `substreams-tier2` correct?

**Comment by matthewdarwin** [comment]
Yes, that's what I was looking it.

**Comment by maoueh** [comment]
Should be fixed now technically, should make its way into a release(s) soon.

**Comment by maoueh** [comment]
`firecore` and `fireeth` has been released we should include the fix, let me know if it looks fine to you.

**Comment by matthewdarwin** [comment]
Seems correct now.
