### ISSUE TITLE
Improve error message `cannot initialize info server: block id encoding is not set`

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/firehose-core#62]
Improve error message `cannot initialize info server: block id encoding is not set`

By default firehose checks for block 0.
If block 0 doesn't exist the server will never start.

Maybe the error message should better suggest what is the problem?  Print which block you're looking for and cannot find.

**Comment by sduchesneau** [comment]
When I start with first-streamable-block=0 instead of 1 (ex. on injective-mainnet), I get these printed out every 5 seconds:

```
2024-09-01T13:05:11.292-0400 WARN (firehose) waiting to read the first_streamable_block before starting firehose/substreams endpoints {"first_streamable_block": 0, "merged_blocks_store": "/my/blocks", "one_block_store": "..."}
```

This is where the info lies.

Anyway, I'm changing the error message to be more explicit, this is how it will look like.

```
################################################################
Fatal error in app firehose:

Error: unable to launch: cannot initialize info server: context deadline exceeded: no block found for first streamable block 0 in the stores or on live source -- use --ignore-advertise-validation to skip these checks```
